# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                (
                    'function',
                    models.CharField(
                        choices=[('MANAGER', 'Gerente'), ('FINANCE', 'Financeiro'), ('ESTIMATOR', 'Orçamentista'), ('OPERATIONAL', 'Operacional')],
                        default='OPERATIONAL',
                        max_length=20,
                    ),
                ),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]

