# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='image_file',
            field=models.FileField(blank=True, upload_to='uploads/collaborators/'),
        ),
    ]

