# Generated by Django 5.2.15 on 2026-06-09 18:08
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_sync_collaborator_emails_to_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="function",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Gerente"),
                    ("FINANCE", "Financeiro"),
                    ("ESTIMATOR", "Orçamentista"),
                    ("OPERATIONAL", "Operacional"),
                    ("VISUAL", "Visual"),
                ],
                default="OPERATIONAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Gerente"),
                    ("FINANCE", "Financeiro"),
                    ("ESTIMATOR", "Orçamentista"),
                    ("OPERATIONAL", "Operacional"),
                    ("VISUAL", "Visual"),
                ],
                default="OPERATIONAL",
                max_length=20,
            ),
        ),
    ]
