# Generated by Django 5.2.15 on 2026-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_collaborator_function_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
