# Generated by Django 5.2.15 on 2026-09-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_collaborator_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeClockDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_at', models.DateTimeField(blank=True, null=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('lunch_out_at', models.DateTimeField(blank=True, null=True)),
                ('lunch_in_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_late', models.IntegerField(default=0)),
                ('minutes_extra', models.IntegerField(default=0)),
                ('minutes_worked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeclock_days', to='users.collaborator')),
            ],
            options={
                'ordering': ('-date', 'collaborator__name', 'id'),
                'unique_together': {('collaborator', 'date')},
            },
        ),
    ]
