# Generated by Django 5.2.15 on 2026-09-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_timeclockday'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclockday',
            name='minutes_missing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='function',
            field=models.CharField(choices=[('MANAGER', 'Gerente'), ('FINANCE', 'Financeiro'), ('ESTIMATOR', 'Orçamentista'), ('OPERATIONAL', 'Operacional'), ('VISUAL', 'Visual'), ('PONTO', 'Ponto (Totem)'), ('TVKANBAN', 'TV Kanban')], default='OPERATIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Gerente'), ('FINANCE', 'Financeiro'), ('ESTIMATOR', 'Orçamentista'), ('OPERATIONAL', 'Operacional'), ('VISUAL', 'Visual'), ('PONTO', 'Ponto (Totem)'), ('TVKANBAN', 'TV Kanban')], default='OPERATIONAL', max_length=20),
        ),
    ]
