from django.urls import path

from .views import (
    BudgetDeleteView,
    BudgetDetailView,
    BudgetFinanceCreateView,
    BudgetListView,
    BudgetOpenListView,
    BudgetUpdateView,
    BudgetXMLDownloadView,
    CiliaXMLImportView,
    CommissionOpenListView,
    CommissionTogglePaidView,
    FinanceDashboardView,
    PieceCreateView,
    PieceDeleteView,
    PieceUpdateView,
    PiecesStatusReportView,
    ServiceCatalogCreateView,
    ServiceCatalogDeleteView,
    ServiceCatalogListView,
    ServiceCatalogUpdateView,
    ThirdPartyServiceCreateView,
    VehicleEntryKanbanView,
    WorkOrderKanbanTodayView,
    WorkOrderDetailView,
    WorkOrderListView,
    WorkOrderTaskFinishView,
    WorkOrderTaskPauseView,
    WorkOrderTaskScheduleView,
    WorkOrderTaskStartView,
    WorkOrderTaskToggleOvertimeView,
)

app_name = 'budgets'

urlpatterns = [
    path('', BudgetListView.as_view(), name='budget_list'),
    path('abertos/', BudgetOpenListView.as_view(), name='budget_open_list'),
    path('financeiro/', FinanceDashboardView.as_view(), name='finance_dashboard'),
    path('kanban-entrada/', VehicleEntryKanbanView.as_view(), name='vehicle_entry_kanban'),
    path('<int:pk>/financeiro/', BudgetFinanceCreateView.as_view(), name='budget_finance_create'),
    path('importar-xml/', CiliaXMLImportView.as_view(), name='import_xml'),
    path('os/', WorkOrderListView.as_view(), name='workorder_list'),
    path('os/<int:pk>/', WorkOrderDetailView.as_view(), name='workorder_detail'),
    path('os/tarefas/<int:pk>/agendar/', WorkOrderTaskScheduleView.as_view(), name='workorder_task_schedule'),
    path('<int:budget_pk>/pecas/novo/', PieceCreateView.as_view(), name='piece_create'),
    path('pecas/<int:pk>/editar/', PieceUpdateView.as_view(), name='piece_update'),
    path('pecas/<int:pk>/excluir/', PieceDeleteView.as_view(), name='piece_delete'),
    path('comissoes/', CommissionOpenListView.as_view(), name='commission_open_list'),
    path('comissoes/<int:pk>/pago/', CommissionTogglePaidView.as_view(), name='commission_toggle_paid'),
    path('relatorios/pecas/', PiecesStatusReportView.as_view(), name='report_pieces'),
    path('kanban/', WorkOrderKanbanTodayView.as_view(), name='kanban_today'),
    path('kanban/tarefas/<int:pk>/iniciar/', WorkOrderTaskStartView.as_view(), name='kanban_task_start'),
    path('kanban/tarefas/<int:pk>/pausar/', WorkOrderTaskPauseView.as_view(), name='kanban_task_pause'),
    path('kanban/tarefas/<int:pk>/finalizar/', WorkOrderTaskFinishView.as_view(), name='kanban_task_finish'),
    path('kanban/tarefas/<int:pk>/extra/', WorkOrderTaskToggleOvertimeView.as_view(), name='kanban_task_extra'),
    path('download/orcamento/<int:cilia_number>/', BudgetXMLDownloadView.as_view(), name='budget_download_xml'),
    path('cadastros/servicos/', ServiceCatalogListView.as_view(), name='service_catalog_list'),
    path('cadastros/servicos/novo/', ServiceCatalogCreateView.as_view(), name='service_catalog_create'),
    path('cadastros/servicos/<int:pk>/editar/', ServiceCatalogUpdateView.as_view(), name='service_catalog_update'),
    path('cadastros/servicos/<int:pk>/excluir/', ServiceCatalogDeleteView.as_view(), name='service_catalog_delete'),
    path('<int:pk>/servicos-terceiros/novo/', ThirdPartyServiceCreateView.as_view(), name='third_party_create'),
    path('<int:pk>/', BudgetDetailView.as_view(), name='budget_detail'),
    path('<int:pk>/editar/', BudgetUpdateView.as_view(), name='budget_update'),
    path('<int:pk>/excluir/', BudgetDeleteView.as_view(), name='budget_delete'),
]
