from django.urls import path

from .views import (
    BudgetDeleteView,
    BudgetDetailView,
    BudgetAdministrativeCloseView,
    BudgetDeliverView,
    BudgetFinanceCreateView,
    PerformanceDashboardView,
    PerformanceInsightsView,
    XMLImportJobDetailView,
    XMLImportJobDeleteDuplicateView,
    XMLImportJobListView,
    XMLImportJobReprocessView,
    BudgetListView,
    BudgetOpenListView,
    BudgetPhotoCreateView,
    BudgetPhotoDeleteView,
    BudgetUpdateView,
    BudgetXMLDownloadView,
    BankAccountCreateView,
    BankAccountDeleteView,
    BankAccountListView,
    BankAccountUpdateView,
    CiliaXMLImportView,
    CommissionOpenListView,
    CommissionTogglePaidView,
    DailyProgrammingReportView,
    FinanceDashboardView,
    FinanceInsightsView,
    FinanceXMLImportView,
    FinanceXMLTemplateDownloadView,
    PieceCreateView,
    PieceDeleteView,
    PieceUpdateView,
    PiecesStatusReportView,
    ServiceCatalogCreateView,
    ServiceCatalogDeleteView,
    ServiceCatalogListView,
    ServiceCatalogUpdateView,
    SupplierCreateView,
    SupplierDeleteView,
    SupplierListView,
    SupplierUpdateView,
    ThirdPartyServiceCreateView,
    ThirdPartyServiceFinishView,
    ThirdPartyServiceUpdateView,
    VehicleEntryKanbanView,
    WorkOrderKanbanTodayView,
    WorkOrderKanbanVisualView,
    WorkOrderOperationalMobileView,
    WorkOrderDetailView,
    WorkOrderListView,
    WorkOrderTaskBulkAssignView,
    WorkOrderTaskBatchCreateView,
    WorkOrderTaskBatchStartView,
    WorkOrderTaskBatchPauseView,
    WorkOrderTaskBatchFinishView,
    WorkOrderTaskFinishView,
    WorkOrderTaskPauseView,
    WorkOrderTaskScheduleView,
    WorkOrderTaskStartView,
    WorkOrderTaskToggleOvertimeView,
)

app_name = 'budgets'

urlpatterns = [
    path('', BudgetListView.as_view(), name='budget_list'),
    path('abertos/', BudgetOpenListView.as_view(), name='budget_open_list'),
    path('financeiro/', FinanceDashboardView.as_view(), name='finance_dashboard'),
    path('financeiro/dash/', FinanceInsightsView.as_view(), name='finance_insights'),
    path('financeiro/importar-xml/', FinanceXMLImportView.as_view(), name='finance_import_xml'),
    path('financeiro/exportar-modelo-xml/', FinanceXMLTemplateDownloadView.as_view(), name='finance_export_xml_template'),
    path('desempenho/', PerformanceDashboardView.as_view(), name='performance_dashboard'),
    path('desempenho/ia/', PerformanceInsightsView.as_view(), name='performance_insights'),
    path('kanban-entrada/', VehicleEntryKanbanView.as_view(), name='vehicle_entry_kanban'),
    path('<int:pk>/financeiro/', BudgetFinanceCreateView.as_view(), name='budget_finance_create'),
    path('<int:pk>/finalizacao-administrativa/', BudgetAdministrativeCloseView.as_view(), name='budget_administrative_close'),
    path('<int:pk>/entregar/', BudgetDeliverView.as_view(), name='budget_deliver'),
    path('importar-xml/', CiliaXMLImportView.as_view(), name='import_xml'),
    path('importacoes/', XMLImportJobListView.as_view(), name='import_job_list'),
    path('importacoes/<int:pk>/', XMLImportJobDetailView.as_view(), name='import_job_detail'),
    path('importacoes/<int:pk>/reprocessar/', XMLImportJobReprocessView.as_view(), name='import_job_reprocess'),
    path('importacoes/<int:pk>/excluir-duplicado/', XMLImportJobDeleteDuplicateView.as_view(), name='import_job_delete_duplicate'),
    path('os/', WorkOrderListView.as_view(), name='workorder_list'),
    path('os/<int:pk>/', WorkOrderDetailView.as_view(), name='workorder_detail'),
    path('os/<int:pk>/tarefas/atribuir-lote/', WorkOrderTaskBulkAssignView.as_view(), name='workorder_task_bulk_assign'),
    path('os/<int:pk>/lotes/criar/', WorkOrderTaskBatchCreateView.as_view(), name='workorder_batch_create'),
    path('lotes/<int:pk>/iniciar/', WorkOrderTaskBatchStartView.as_view(), name='workorder_batch_start'),
    path('lotes/<int:pk>/pausar/', WorkOrderTaskBatchPauseView.as_view(), name='workorder_batch_pause'),
    path('lotes/<int:pk>/finalizar/', WorkOrderTaskBatchFinishView.as_view(), name='workorder_batch_finish'),
    path('os/tarefas/<int:pk>/agendar/', WorkOrderTaskScheduleView.as_view(), name='workorder_task_schedule'),
    path('<int:budget_pk>/pecas/novo/', PieceCreateView.as_view(), name='piece_create'),
    path('pecas/<int:pk>/editar/', PieceUpdateView.as_view(), name='piece_update'),
    path('pecas/<int:pk>/excluir/', PieceDeleteView.as_view(), name='piece_delete'),
    path('comissoes/', CommissionOpenListView.as_view(), name='commission_open_list'),
    path('comissoes/<int:pk>/pago/', CommissionTogglePaidView.as_view(), name='commission_toggle_paid'),
    path('relatorios/pecas/', PiecesStatusReportView.as_view(), name='report_pieces'),
    path('relatorios/programacao-diaria/', DailyProgrammingReportView.as_view(), name='report_daily_programming'),
    path('kanban/', WorkOrderKanbanTodayView.as_view(), name='kanban_today'),
    path('kanban/tv/', WorkOrderKanbanVisualView.as_view(), name='kanban_tv'),
    path('kanban/meu/', WorkOrderOperationalMobileView.as_view(), name='kanban_my_tasks'),
    path('kanban/tarefas/<int:pk>/iniciar/', WorkOrderTaskStartView.as_view(), name='kanban_task_start'),
    path('kanban/tarefas/<int:pk>/pausar/', WorkOrderTaskPauseView.as_view(), name='kanban_task_pause'),
    path('kanban/tarefas/<int:pk>/finalizar/', WorkOrderTaskFinishView.as_view(), name='kanban_task_finish'),
    path('kanban/tarefas/<int:pk>/extra/', WorkOrderTaskToggleOvertimeView.as_view(), name='kanban_task_extra'),
    path('download/orcamento/<int:cilia_number>/', BudgetXMLDownloadView.as_view(), name='budget_download_xml'),
    path('cadastros/servicos/', ServiceCatalogListView.as_view(), name='service_catalog_list'),
    path('cadastros/servicos/novo/', ServiceCatalogCreateView.as_view(), name='service_catalog_create'),
    path('cadastros/servicos/<int:pk>/editar/', ServiceCatalogUpdateView.as_view(), name='service_catalog_update'),
    path('cadastros/servicos/<int:pk>/excluir/', ServiceCatalogDeleteView.as_view(), name='service_catalog_delete'),
    path('cadastros/bancos/', BankAccountListView.as_view(), name='bank_account_list'),
    path('cadastros/bancos/novo/', BankAccountCreateView.as_view(), name='bank_account_create'),
    path('cadastros/bancos/<int:pk>/editar/', BankAccountUpdateView.as_view(), name='bank_account_update'),
    path('cadastros/bancos/<int:pk>/excluir/', BankAccountDeleteView.as_view(), name='bank_account_delete'),
    path('cadastros/fornecedores/', SupplierListView.as_view(), name='supplier_list'),
    path('cadastros/fornecedores/novo/', SupplierCreateView.as_view(), name='supplier_create'),
    path('cadastros/fornecedores/<int:pk>/editar/', SupplierUpdateView.as_view(), name='supplier_update'),
    path('cadastros/fornecedores/<int:pk>/excluir/', SupplierDeleteView.as_view(), name='supplier_delete'),
    path('<int:pk>/servicos-terceiros/novo/', ThirdPartyServiceCreateView.as_view(), name='third_party_create'),
    path('servicos-terceiros/<int:pk>/editar/', ThirdPartyServiceUpdateView.as_view(), name='third_party_update'),
    path('servicos-terceiros/<int:pk>/finalizar/', ThirdPartyServiceFinishView.as_view(), name='third_party_finish'),
    path('<int:pk>/fotos/nova/', BudgetPhotoCreateView.as_view(), name='budget_photo_create'),
    path('fotos/<int:pk>/excluir/', BudgetPhotoDeleteView.as_view(), name='budget_photo_delete'),
    path('<int:pk>/', BudgetDetailView.as_view(), name='budget_detail'),
    path('<int:pk>/editar/', BudgetUpdateView.as_view(), name='budget_update'),
    path('<int:pk>/excluir/', BudgetDeleteView.as_view(), name='budget_delete'),
]
