# Generated by Django 5.2.15 on 2026-06-05 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Resposta'), ('AUTHORIZED', 'Autorizada'), ('NOT_APPROVED', 'Não Aprovada')], default='PENDING', max_length=20)),
                ('refusal_reason', models.CharField(blank=True, max_length=255)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('repair_start_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='customers.vehicle')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider_type', models.CharField(choices=[('CUSTOMER', 'Cliente'), ('INSURER', 'Seguradora'), ('SHOP', 'Oficina')], default='SHOP', max_length=20)),
                ('arrived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='budgets.budget')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
