# Generated by Django 5.2.15 on 2026-06-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_discount_total_budget_labor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='source_xml',
            field=models.TextField(blank=True),
        ),
    ]
