# Generated by Django 5.2.15 on 2026-06-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_source_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='cilia_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='cilia_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
