# Generated by Django 5.2.15 on 2026-06-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget_cilia_number_budget_cilia_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'budget',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='third_party_services',
                        to='budgets.budget',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]

