# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_thirdpartyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]

