# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_budget_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='refusal_reason_code',
            field=models.CharField(blank=True, choices=[('TOO_EXPENSIVE', 'Achou caro'), ('NO_MONEY', 'Não tem dinheiro para fazer o serviço'), ('OTHER_SHOP', 'Vai procurar outra oficina'), ('CLAIM_PROOF', 'Orçamento só para comprovação de sinistro'), ('INSURANCE', 'Vai acionar o seguro'), ('SOLD_VEHICLE', 'Vendeu o veículo'), ('NO_RESPONSE', 'Sem retorno do cliente')], max_length=40),
        ),
    ]

