# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_budget_refusal_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='parent_budget',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='complements',
                to='budgets.budget',
            ),
        ),
        migrations.AddField(
            model_name='budget',
            name='complement_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]

