# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collaborator'),
        ('budgets', '0008_budget_parent_budget_budget_complement_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('default_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Fechada')], default='OPEN', max_length=10)),
                ('vehicle_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'budget',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='work_order',
                        to='budgets.budget',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'activity',
                    models.CharField(
                        choices=[
                            ('DISMANTLING', 'Desmontagem'),
                            ('BODYWORK', 'Funilaria'),
                            ('PREPARATION', 'Preparação'),
                            ('PAINTING', 'Pintura'),
                            ('ASSEMBLY', 'Montagem'),
                            ('POLISHING', 'Polimento'),
                            ('DELIVERY_PREP', 'Prep Entrega'),
                        ],
                        max_length=20,
                    ),
                ),
                ('description', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    'status',
                    models.CharField(
                        choices=[('SCHEDULED', 'Agendado'), ('DONE', 'Concluído')],
                        default='SCHEDULED',
                        max_length=20,
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'collaborator',
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.collaborator'),
                ),
                (
                    'work_order',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='budgets.workorder'),
                ),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'collaborator',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.collaborator'),
                ),
                (
                    'task',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='budgets.workordertask'),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]

