# Generated by Django 5.2.15 on 2026-06-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0027_budget_delivered_at_budget_delivered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyservice',
            name='expense_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_party_services', to='budgets.cashmovement'),
        ),
        migrations.AddField(
            model_name='thirdpartyservice',
            name='is_shop_service',
            field=models.BooleanField(default=False),
        ),
    ]
