# Generated by Django 5.2.15 on 2026-08-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0028_thirdpartyservice_expense_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('PARTICULAR', 'Particular'), ('INSURER', 'Seguradora'), ('COMPANY', 'Empresa')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('PARTICULAR', 'Particular'), ('INSURER', 'Seguradora'), ('COMPANY', 'Empresa')], max_length=20, null=True),
        ),
    ]
