# Generated by Django 5.2.15 on 2026-08-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0031_customer_type_on_budget_and_cashmovement'),
        ('users', '0007_alter_collaborator_function_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTaskBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('DISMANTLING', 'Desmontagem'), ('BODYWORK', 'Funilaria'), ('PREPARATION', 'Preparação'), ('PAINTING', 'Pintura'), ('ASSEMBLY', 'Montagem'), ('POLISHING', 'Polimento'), ('DELIVERY_PREP', 'Prep Entrega')], max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('RUNNING', 'Em andamento'), ('PAUSED', 'Pausado'), ('DONE', 'Concluído')], default='SCHEDULED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.collaborator')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='budgets.workorder')),
            ],
            options={
                'verbose_name': 'Lote de Tarefas (OS)',
                'verbose_name_plural': 'Lotes de Tarefas (OS)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='workordertask',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='budgets.workordertaskbatch'),
        ),
    ]
