# Generated by Django 5.2.15 on 2026-08-30 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0032_workordertaskbatch_workordertask_batch'),
        ('customers', '0002_vehicle_image_file'),
        ('users', '0008_collaborator_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFinanceQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ZAP_API', max_length=40)),
                ('external_message_id', models.CharField(blank=True, max_length=120)),
                ('duplicate_key', models.CharField(max_length=64, unique=True)),
                ('sender_phone', models.CharField(blank=True, max_length=40)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('chat_id', models.CharField(blank=True, max_length=120)),
                ('chat_name', models.CharField(blank=True, max_length=255)),
                ('is_group_message', models.BooleanField(default=False)),
                ('message_text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('command_name', models.CharField(blank=True, max_length=40)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('direction', models.CharField(blank=True, choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('REJECTED', 'Recusado'), ('DUPLICATE', 'Duplicado'), ('IGNORED', 'Ignorado')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_items', to='budgets.bankaccount')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_items', to='budgets.budget')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_items', to='budgets.cashcategory')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_items', to='users.collaborator')),
                ('confirmed_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_items', to='budgets.cashmovement')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_items', to='customers.customer')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='budgets.whatsappfinancequeueitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_whatsapp_queue_items', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_queue_items', to='budgets.supplier')),
            ],
            options={
                'verbose_name': 'Fila financeira WhatsApp',
                'verbose_name_plural': 'Fila financeira WhatsApp',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ZAP_API', max_length=40)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('external_message_id', models.CharField(blank=True, max_length=120)),
                ('sender_phone', models.CharField(blank=True, max_length=40)),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('chat_id', models.CharField(blank=True, max_length=120)),
                ('chat_name', models.CharField(blank=True, max_length=255)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed_ok', models.BooleanField(default=False)),
                ('duplicate_key', models.CharField(blank=True, max_length=64)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='budgets.whatsappfinancequeueitem')),
            ],
            options={
                'verbose_name': 'Log Webhook WhatsApp',
                'verbose_name_plural': 'Logs Webhook WhatsApp',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
