# Generated by Django 5.2.15 on 2026-09-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0033_whatsappfinancequeueitem_whatsappwebhooklog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppFinanceQueueAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="whatsapp/finance_queue/%Y/%m/%d/"),
                ),
                ("mimetype", models.CharField(blank=True, max_length=100)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="budgets.whatsappfinancequeueitem",
                    ),
                ),
            ],
        ),
    ]
